[package]
name = "api-cinema-rust"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"

[package.metadata]
author = ["BrunoF2P <brunobispof2p@gmail.com>"]
repository = "https://github.com/BrunoF2P/api-cinema-rust"

[dependencies]
