name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.82.0  # 'toolchain' é o parâmetro correto

    - name: Install dependencies
      run: |
        cargo build

    - name: Run tests
      run: |
        cargo test

    - name: Build the application
      run: |
        cargo build --release

    - name: Build Docker image
      if: success() && github.ref == 'refs/heads/main'
      run: |
        docker build -t api-cinema-rust .

    - name: Push Docker image to Docker Hub
      if: success() && github.ref == 'refs/heads/main' 
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag api-cinema-rust $DOCKER_USERNAME/api-cinema-rust:latest
        docker push $DOCKER_USERNAME/api-cinema-rust:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
